name: Daily Haiku Deploy

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *"  # Runs daily at 8:00 UTC (4am Eastern)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install openai

      - name: Run haiku generator
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python generate_haikus.py

      - name: Commit generated files
        run: |
          git config --global user.name "ClamBakeSantaBot"
          git config --global user.email "bot@example.com"
          git add docs/
          git commit -m "Update haiku output" || echo "Nothing to commit"
          git push
