name: Daily Haiku Deploy

on:
  schedule:
    - cron: '0 8 * * *'  # Runs daily at 08:00 UTC (4:00 AM Eastern)
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # 🔑 disables default token

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run haiku generator
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        run: python generate_haikus.py

      - name: Push changes back to GitHub
        run: |
          git config user.name "ClamBakeSantaBot"
          git config user.email "bot@clambakesanta.local"
          git add .
          git commit -m "Daily haiku update" || echo "Nothing to commit"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git main
