name: Generate and Deploy Haikus

on:
  schedule:
    - cron: '0 8 * * *'  # 08:00 UTC = 4:00 AM Eastern
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install openai

      - name: Run haiku generator
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_USER: ${{ secrets.FTP_USER }}
          FTP_PASS: ${{ secrets.FTP_PASS }}
        run: python generate_haikus.py

      - name: Commit and push generated files
        run: |
          git config user.name "ClamBakeSantaBot"
          git config user.email "bot@example.com"
          git add docs/
          git commit -m "🤖 Daily haiku update"
          git push
