name: Deploy Daily Haikus

on:
  schedule:
    - cron: '0 8 * * *'  # Runs at 08:00 UTC daily
  workflow_dispatch:     # Allows manual trigger

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai python-dotenv

      - name: Run haiku generator
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_USER: ${{ secrets.FTP_USER }}
          FTP_PASS: ${{ secrets.FTP_PASS }}
        run: python generate_haikus.py
