name: Daily Haiku Deploy

on:
  schedule:
    - cron: '0 8 * * *'  # 08:00 UTC = 4:00 AM Eastern
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install openai

      - name: Run Haiku Generator
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_USER: ${{ secrets.FTP_USER }}
          FTP_PASS: ${{ secrets.FTP_PASS }}
        run: |
          mkdir -p docs/archives
          python generate_haikus.py

      - name: Commit and Push to GitHub Pages
        run: |
          git config user.name "ClamBakeSantaBot"
          git config user.email "bot@example.com"
          git add docs/
          git commit -m "Daily haiku update"
          git push origin main
