name: Daily Haiku Deploy

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *"

jobs:
  generate-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install openai

      - name: Set OpenAI API key
        run: echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV

      - name: Run haiku generator
        run: python generate_haikus.py

      - name: Commit and push docs folder
        run: |
          git config user.name "ClamBakeSantaBot"
          git config user.email "stephen.pleasants@gmail.com"
          git add docs/
          git commit -m "Update GitHub Pages content" || echo "No changes to commit"
          git push
